# Use the official Nginx image as the base
FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom configuration files from the `nginx` directory into the container
COPY ./nginx/zerodaypoke.com.conf /etc/nginx/conf.d/
# COPY ./nginx/strain.gg.conf /etc/nginx/conf.d/

# Expose ports (docker-compose will handle the port mapping)
EXPOSE 80 443

# Default command to run when the container starts
CMD ["nginx", "-g", "daemon off;"]
