"""links

Revision ID: 24e228d84643
Revises: de838e0e24f4
Create Date: 2023-05-28 00:18:51.283924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e228d84643'
down_revision = 'de838e0e24f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('live_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('live_link')
        batch_op.drop_column('repo_link')

    # ### end Alembic commands ###
