"""dynamic misc link naming

Revision ID: 26857b06e601
Revises: 304549b90ed1
Create Date: 2023-10-18 18:48:18.026259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26857b06e601'
down_revision = '304549b90ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('misc_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('misc_name')

    # ### end Alembic commands ###
