"""add misc field

Revision ID: 304549b90ed1
Revises: 2b759c221859
Create Date: 2023-10-18 18:43:48.982969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '304549b90ed1'
down_revision = '2b759c221859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
