"""add tutorial model

Revision ID: 8d992b2dde07
Revises: 471a1bee5c65
Create Date: 2023-10-04 02:33:37.084849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d992b2dde07'
down_revision = '471a1bee5c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorials',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('content_file', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutorial_skills',
    sa.Column('tutorial_id', sa.String(length=60), nullable=False),
    sa.Column('skill_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ),
    sa.PrimaryKeyConstraint('tutorial_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorial_skills')
    op.drop_table('tutorials')
    # ### end Alembic commands ###
